---
- name: Install zabbix_release package from zabbix repo
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution|lower }}/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_release_version }}%2B{{ ansible_distribution|lower }}{{ ansible_distribution_version }}_all.deb

- name: Update packages library
  ansible.builtin.apt:
    name: zabbix-agent2
    update_cache: yes

- name: Change config of zabbix-agent2
  template:
    src: ./templates/zabbix_agent2.conf.j2
    dest: "/etc/zabbix/zabbix_agent2.conf"
    owner: root