- name: allow ssh
  ufw:
    rule: allow
    port: 44122
    proto: tcp

- name: allow zabbix
  ufw:
    rule: allow
    port: 10050:10051
    proto: tcp

- name: allow postgresql connection
  ufw:
    rule: allow
    port: 5432
    proto: tcp

