- name: allow ssh
  ufw:
    rule: allow
    port: {{ssh_port}}
    proto: tcp

- name: allow zabbix
  ufw:
    rule: allow
    port: {{zabbix_port}}
    proto: tcp

- name: allow postgresql connection
  ufw:
    rule: allow
    port: {{postgres_port}}
    proto: tcp

- name: Enable ufw
  ufw:
    state: enabled

